package(default_visibility = ["//visibility:public"])
cc_binary(
  name = "main",
  srcs = ["main.cc"],
  deps = [
    "//network:mem_channel",
    "//network:channel_interface",
    "@com_google_googletest//:gtest_main",
  ],
)
